COPY aka_name FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/aka_name.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY aka_title FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/aka_title.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY cast_info FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/cast_info.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY char_name FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/char_name.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY comp_cast_type FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/comp_cast_type.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY company_name FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/company_name.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY company_type FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/company_type.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY complete_cast FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/complete_cast.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY info_type FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/info_type.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY keyword FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/keyword.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY kind_type FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/kind_type.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY link_type FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/link_type.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY movie_companies FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/movie_companies.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY movie_info_idx FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/movie_info_idx.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY movie_keyword FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/movie_keyword.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY movie_link FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/movie_link.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY name FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/ name.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY role_type FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/role_type.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY title FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/title.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);
COPY movie_info FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/movie_info.csv'' (FORMAT ''csv'', quote ''" '', delimiter '','', header 0);
COPY person_info FROM ''/Users/chuyinghe/CLionProjects/duckdb-rl/imdb/person_info.csv '' (FORMAT '' csv '', quote '' "'', delimiter '','', header 0);